mkdir Animations
mkdir Audios
mkdir Audios\Effects
mkdir Audios\Musics
mkdir Docs
mkdir Fonts
mkdir Materials
mkdir Prefabs
mkdir Prefabs\Actors
mkdir Prefabs\Actors\Enemies
mkdir Prefabs\Actors\Player
mkdir Prefabs\Actors\Collectables
mkdir Prefabs\Actors\Enemies
mkdir Prefabs\GUI
mkdir Scenes
mkdir Scenes\Cameras
mkdir Scenes\Levels
mkdir Scenes\Menus
mkdir Scenes\Settings
mkdir Scenes\Splash
mkdir Scenes\Tests
mkdir Scripts
mkdir Scripts\Debug
mkdir Scripts\Native
mkdir Scripts\ThirdParty
mkdir Sprites
mkdir Sprites\About
mkdir Sprites\Actors
mkdir Sprites\Grounds
mkdir Sprites\Icons
mkdir Sprites\Items
mkdir Sprites\Levels
mkdir Sprites\UI
mkdir Textures
mkdir Textures

pause